// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xybcrcioyapuhqvmtqnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5YmNyY2lveWFwdWhxdm10cW5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NDQ1MTYsImV4cCI6MjA3MDEyMDUxNn0.68CYn6VMuy4Wsns6Qng_GJHd4S8H6vn6nJbBWjednvU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});